**Exploring Hacker News Posts**

Hacker News is a popular technology news site where users submit links and ask questions. You’ll analyze two post types, “Ask HN” and “Show HN” to figure out what makes a post get traction. Clean data, real questions, solid practice with Python string handling and datetime analysis.

*Step-by-Step Instructions:*

1.  Load the CSV and explore the columns:
title, URL, points, comments, time.
2.  Separate posts into “Ask HN”, “Show HN”, and other categories.
3.  Calculate average comments for each type.
4.  Parse the created_at column using the datetime module.
5.  Find which hours produce the most comments for Ask HN posts.
6.  Summarize findings in plain language.

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("hacker-news/hacker-news-posts")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'hacker-news-posts' dataset.
Path to dataset files: /kaggle/input/hacker-news-posts

1.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('HN_posts_year_to_Sep_26_2016.csv')
df.head(5)

,id,title,url,num_points,num_comments,author,created_at
0,12579008,You have two days to comment if you want stem ...,http://www.regulations.gov/document?D=FDA-2015...,1,0,altstar,9/26/2016 3:26
1,12579005,SQLAR the SQLite Archiver,https://www.sqlite.org/sqlar/doc/trunk/README.md,1,0,blacksqr,9/26/2016 3:24
2,12578997,What if we just printed a flatscreen televisio...,https://medium.com/vanmoof/our-secrets-out-f21...,1,0,pavel_lishin,9/26/2016 3:19
3,12578989,algorithmic music,http://cacm.acm.org/magazines/2011/7/109891-al...,1,0,poindontcare,9/26/2016 3:16
4,12578979,How the Data Vault Enables the Next-Gen Data W...,https://www.talend.com/blog/2016/05/12/talend-...,1,0,markgainor1,9/26/2016 3:14

In [4]:
df = df[['title', 'url', 'num_points', 'num_comments', 'created_at']]
df.rename(columns={'num_points': 'points', 'url' : 'URL', 'num_comments': 'Comments', 'created_at': 'Time'}, inplace=True)
df.head(5)

,title,URL,points,Comments,Time
0,You have two days to comment if you want stem ...,http://www.regulations.gov/document?D=FDA-2015...,1,0,9/26/2016 3:26
1,SQLAR the SQLite Archiver,https://www.sqlite.org/sqlar/doc/trunk/README.md,1,0,9/26/2016 3:24
2,What if we just printed a flatscreen televisio...,https://medium.com/vanmoof/our-secrets-out-f21...,1,0,9/26/2016 3:19
3,algorithmic music,http://cacm.acm.org/magazines/2011/7/109891-al...,1,0,9/26/2016 3:16
4,How the Data Vault Enables the Next-Gen Data W...,https://www.talend.com/blog/2016/05/12/talend-...,1,0,9/26/2016 3:14

2.

In [5]:
def categorize_title(title):
    if str(title).lower().startswith('ask hn'):
        return 'ask hn'
    elif str(title).lower().startswith('show hn'):
        return 'show hn'
    else:
        return 'others'

df['title_category'] = df['title'].apply(categorize_title)
print(df['title_category'].value_counts())
df.head(5)

title_category
others     273822
show hn     10158
ask hn       9139
Name: count, dtype: int64

,title,URL,points,Comments,Time,title_category
0,You have two days to comment if you want stem ...,http://www.regulations.gov/document?D=FDA-2015...,1,0,9/26/2016 3:26,others
1,SQLAR the SQLite Archiver,https://www.sqlite.org/sqlar/doc/trunk/README.md,1,0,9/26/2016 3:24,others
2,What if we just printed a flatscreen televisio...,https://medium.com/vanmoof/our-secrets-out-f21...,1,0,9/26/2016 3:19,others
3,algorithmic music,http://cacm.acm.org/magazines/2011/7/109891-al...,1,0,9/26/2016 3:16,others
4,How the Data Vault Enables the Next-Gen Data W...,https://www.talend.com/blog/2016/05/12/talend-...,1,0,9/26/2016 3:14,others

3.

In [6]:
a = df[df['title_category'] == 'ask hn']['Comments'].mean()
b = df[df['title_category'] == 'show hn']['Comments'].mean()
c = df[df['title_category'] == 'others']['Comments'].mean()
print("Ask HN average comments:", a)
print("Show HN average comments:", b)
print("Others average comments:", c)

Ask HN average comments: 10.393478498741656
Show HN average comments: 4.886099625910612
Others average comments: 6.4572678601427205

4.

In [7]:
df['Time'] = pd.to_datetime(df['Time'])
df.head()

,title,URL,points,Comments,Time,title_category
0,You have two days to comment if you want stem ...,http://www.regulations.gov/document?D=FDA-2015...,1,0,2016-09-26 03:26:00,others
1,SQLAR the SQLite Archiver,https://www.sqlite.org/sqlar/doc/trunk/README.md,1,0,2016-09-26 03:24:00,others
2,What if we just printed a flatscreen televisio...,https://medium.com/vanmoof/our-secrets-out-f21...,1,0,2016-09-26 03:19:00,others
3,algorithmic music,http://cacm.acm.org/magazines/2011/7/109891-al...,1,0,2016-09-26 03:16:00,others
4,How the Data Vault Enables the Next-Gen Data W...,https://www.talend.com/blog/2016/05/12/talend-...,1,0,2016-09-26 03:14:00,others

In [8]:
df['Time'].dtype

dtype('<M8[ns]')

5.

In [9]:
b2 = df[df['title_category'] == 'show hn']['Comments'].sort_values(ascending=False).index
df['Time'].iloc[b2]

103703   2016-05-10 14:39:00
218293   2015-12-14 02:24:00
8216     2016-09-15 07:07:00
273140   2015-10-02 18:56:00
251128   2015-10-30 13:45:00
                 ...
1288     2016-09-23 16:37:00
1328     2016-09-23 15:55:00
1338     2016-09-23 15:43:00
292772   2015-09-07 00:20:00
292778   2015-09-06 23:57:00
Name: Time, Length: 10158, dtype: datetime64[ns]